### ISSUE TITLE
Sushiswap addresses on Arbitrum testnet

### ISSUE THREAD

**Issue by cfengliu** [sushiswap/sdk#18]
Hi all, how can I get sushiswap factory, router addresses on arbitrum testnet? There is no address for arbitrum testnet in this [page](https://github.com/sushiswap/sdk/blob/canary/packages/core-sdk/src/constants/addresses.ts).

**Comment by matthewlilley** [comment]
> Hi all, how can I get sushiswap factory, router addresses on arbitrum testnet? There is no address for arbitrum testnet in this [page](https://github.com/sushiswap/sdk/blob/canary/packages/core-sdk/src/constants/addresses.ts).

There isn't a deployment on the testnet, but might look to add one later.
